object Plugins {
    const val ANDROID_APPLICATION = "com.android.application"
    const val ANDROID_LIBRARY = "com.android.library"
    const val JVM = "jvm"
    const val KOTLIN = "kotlin"
    const val KOTLIN_ANDROID = "android"
    const val KOTLIN_KAPT = "kapt"
    const val KOTLIN_MULTIPLATFORM = "multiplatform"
    const val SERIALIZATION = "plugin.serialization"
    const val JETBRAINS_COMPOSE = "org.jetbrains.compose"
    const val COCAPODS = "native.cocoapods"
    const val SHADOW = "com.github.johnrengelman.shadow"
    const val SQL_DELIGHT = "com.squareup.sqldelight"
    const val KOTEST_MULTIPLATFORM = "io.kotest.multiplatform"
    const val KOVER = "org.jetbrains.kotlinx.kover"
}